TF-440: Remove demo (poc) mode
hashicorp/terraform-random-tfe-utility pull request #10
Opened 2022-03-01 23:32 UTC by sudomateo

## Background

Removing the demo (`poc`) installation mode to get ready for the April release of Terraform Enterprise where it will be removed in the code.

## How Has This Been Tested

Use the module and confirm the outputted settings file does not contain `installation_type` and that the `production_type` is `disk` for mounted disk installations and `external` for external services installations.

## TFE Modules

### Did you add a new setting?

No, I removed one.

## This PR makes me feel

![optional gif describing your feelings about this pr](https://media.giphy.com/media/m9eG1qVjvN56H0MXt8/giphy.gif)

2022-03-02 16:38 UTC, theoskolnik approved these changes

2022-03-07 17:15 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +  default     = "disk"
We want this module to be completely unopinionated, including with defaults, so this would remain `null`.
```suggestion
  default     = null
```

2022-03-07 17:18 UTC, anniehedgpeth requested changes
This will be great to get rid of POC! Whenever you test this change, if you could just link the passing tests, that'd be great. I know, I know, CI is on the backlog!  😬

2022-03-07 17:18 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +      var.production_type == "disk"
```suggestion
      var.production_type == "disk" ||
      var.production_type == null
```
See above comment.

2022-03-12 18:27 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-random-tfe-utility?pullRequest=10)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-random-tfe-utility?pullRequest=10)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-random-tfe-utility?pullRequest=10).</sub>

2022-03-30 17:29 UTC, anniehedgpeth reviewed
Just a little formatted request and waiting on tests. Other than that, yay!

2022-03-30 17:29 UTC, anniehedgpeth commented on modules/settings/variables.tf
>    EOD
Would you mind aligning this to the beginning of `description` for consistency?

2022-04-22 20:49 UTC, sudomateo commented
Here's the link to the passing tests that were needed before we can merge this https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/155#issuecomment-1106819523.

2022-04-22 22:49 UTC, anniehedgpeth commented
- [ ] [Replicated Tests](https://app.circleci.com/pipelines/github/hashicorp/ptfe-replicated?branch=test-demo-deprecation&filter=all) pass
- [x] [Azure TFE tests](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/155#issuecomment-1106819523) pass
- [x] [AWS TFE tests](https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/240#issuecomment-1106912108) pass
- [x] [Google TFE tests](https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/152#issuecomment-1106912208) pass

2022-04-22 22:55 UTC, anniehedgpeth commented
@sudomateo Looks like Azure will need `~> 1.0` Terraform version to fix [these failed tests](https://app.circleci.com/pipelines/github/hashicorp/ptfe-replicated?branch=test-demo-deprecation&filter=all).

2022-04-23 00:02 UTC, anniehedgpeth approved these changes
ready to go!

2022-04-23 00:05 UTC, merged