add: allow setting daemonauthpassword if migrating configurations
hashicorp/terraform-random-tfe-utility pull request #107
Opened 2023-06-27 11:18 UTC by arnvid

## Background

In cases when there is an existing TFE installation, upgrade, migration or recovery it can be necessary to deploy with an existing daemonauthpassword.

## How has this been tested?
Tested on deploying onto an existing config.

## TFE Modules

### Did you add a new setting?
Added a new variable daemonauthpassword for settings module .

- [ ] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [ ] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [ ] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

Do not have any ability to test on Azure or GCP.

2023-06-27 11:18 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-random-tfe-utility?pullRequest=107)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-random-tfe-utility?pullRequest=107)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Arnvid Karstad** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-random-tfe-utility?pullRequest=107).</sub>

2023-06-28 15:46 UTC, anniehedgpeth requested changes
Thank you for this PR! I appreciate the submission! I have suggested some minor changes for consistency and tidiness. After those changes are in, I can run tests to ensure it passes before approving and merging.

2023-06-28 15:46 UTC, anniehedgpeth commented on modules/settings/replicated_config.tf
> +    DaemonAuthenticationPassword      = coalesce(var.daemonauthpassword, random_string.password.result)
```suggestion
    DaemonAuthenticationPassword      = coalesce(var.daemon_auth_password, random_string.password.result)
```

2023-06-28 15:46 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +}
```suggestion
variable "daemon_auth_password" {
  default     = null
  type        = string
  description = <<-EOD
  (Optional) This password allows access to the daemon authentication. If unset, it will create a new one.
  EOD
}
```

Just a little tidying up of the wording. 

Also, can you move this to the `Replicated` section in alphabetical order, so after `bypass_preflight_checks`?

2023-06-30 14:05 UTC, arnvid commented
Hi @anniehedgpeth - I have updated the branch.

2023-06-30 14:52 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +  (Optional) This Password allows access to the daemon authentication - may be set if going between installations. If unset, it will create a new oneg.
```suggestion
  (Optional) This password allows access to the daemon authentication. If unset, it will create a new one.
```

2023-06-30 20:15 UTC, arnvid commented
Sorry for the typo.

2023-11-02 21:39 UTC, closed without merging