Add template to enable log forwarding for the clouds - 2
hashicorp/terraform-random-tfe-utility pull request #109
Opened 2023-06-29 19:03 UTC by edwardsitj-stratascale

## Background

Found a gap in the init script where it would be beneficial to have log forwarding in the user_data for certain clouds. This is especially helpful if it is an autoscale group or scale set.

Relates OR Closes #0000

## How has this been tested?

Validated that it generated the script template correctly and did not affect existing templates. Have not tested the log forwarding settings in each of the clouds.

## TFE Modules

### Did you add a new setting?

If no, you may delete these tasks.
If yes, please check each box after you have have added an issue in the TFE modules to add this setting:

- [x] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [x] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [x] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

## This PR makes me feel

![optional gif describing your feelings about this pr]()

2023-07-07 22:06 UTC, anniehedgpeth commented
Thank you so much for your contribution! This is definitely something we needed to add, so your PR is much appreciated. I will review and test this next week.

2023-07-10 16:31 UTC, anniehedgpeth requested changes
Hey @edwardsitj-stratascale, I had a chance to look at your PR, and we so appreciate all the work you put into it! 

I have a comment below about the overall design that I'm hoping isn't too much work to move around. If you don't have time to address it, then we can certainly put it on our backlog for some point soon. 

And please let me know if you understand what I'm saying. It was a little difficult to describe. :D 

Thanks!

2023-07-10 20:18 UTC, edwardsitj-stratascale commented
> Hey @edwardsitj-stratascale, I had a chance to look at your PR, and we so appreciate all the work you put into it!
> 
> I have a comment below about the overall design that I'm hoping isn't too much work to move around. If you don't have time to address it, then we can certainly put it on our backlog for some point soon.
> 
> And please let me know if you understand what I'm saying. It was a little difficult to describe. :D
> 
> Thanks!

2023-07-10 20:22 UTC, edwardsitj-stratascale commented on modules/tfe_init/main.tf
> +    }
Hi @anniehedgpeth , I made the recommended changes. I found that log_forwarding_config was already listed in the settings module although it looks incomplete. I added the additional variable object and passed it as a new local called log_forwarding_cloud_config to be merged in to the tfe_configuration.

I also added the log_forwarding_config to the setup_log_forwarding script template so that users could still pass the fluentbit config as a string if needed.

2023-07-10 20:26 UTC, edwardsitj-stratascale commented on modules/settings/tfe_base_external_config.tf
> +    pg_extra_params = {
I kept getting an error here when I would plan that false did not have the pg_extra_params attribute. Not sure if it broke in a later version of terraform.

2025-06-30 11:10 UTC, nikolasrieble commented
We intend to archive this repository, and do not support further extension. For guidance on deploying TFE, please refer to our publicly documented modules, see https://developer.hashicorp.com/terraform/enterprise/deploy#terraform-module-workflow

2025-06-30 11:10 UTC, closed without merging