Readme template
hashicorp/terraform-random-tfe-utility pull request #18
Opened 2022-04-22 14:35 UTC by sandrampeter

## Background
 
[ASANA](https://app.asana.com/0/1200681690870921/1202157051958523/f)

Base template will be used for creating README.md file for examples in terraform-*-terraform-enterprise

2022-04-22 16:08 UTC, anniehedgpeth commented on template.README.md
> +*This section provides step-by-step instructions on how to run the module for each cloud provider. This includes steps on how to set credentials, provider block, creating any local files such as terr
For everything that is common across clouds, you can add that "hardcoded" information into the template so that we can prevent any sort of variation.

2022-04-22 16:15 UTC, anniehedgpeth commented on template.README.md
> +# EXAMPLE: *Name of the example TFE installation*
```suggestion
# EXAMPLE: [standalone/AA], [operational type], [environment (optional)] Installation of Terraform Enterprise
```
To ensure consistency, I think we should prescribe how we formulate the names of the variables.

2022-04-22 16:17 UTC, anniehedgpeth commented on template.README.md
> +- List of traits of the example installation
Can you list here the traits that should be included in each list? i.e. instance size, installation type, etc.

2022-04-22 16:18 UTC, anniehedgpeth commented on template.README.md
> +- List of prerequisites that the module assumes
Can you list here all of the possible prerequisites that there are to choose from? That way the list is always consistently worded?

2022-04-22 16:18 UTC, anniehedgpeth commented on template.README.md
> +*This section describes activities after deployment is triggered. If a proxy is deployed, provide instructions to set up local connection to the proxy as well.*
Can you add the proxy instructions to this template?

2022-04-22 16:20 UTC, anniehedgpeth commented
Instead of having this in the top level, I think we should have a dedicated directory for things like this. Perhaps a good place is `fixtures/files`?

2022-04-25 21:46 UTC, sandrampeter commented on template.README.md
> +*This section describes activities after deployment is triggered. If a proxy is deployed, provide instructions to set up local connection to the proxy as well.*
Added

2022-04-25 22:26 UTC, sandrampeter commented on template.README.md
> +- List of prerequisites that the module assumes
Updated with the basic prerequisites. I might have to add in few more as I work through the examples [task](https://app.asana.com/0/1200681690870921/1202157051958539/f)

2022-04-26 16:54 UTC, anniehedgpeth commented on templates/template.README.md
> +      - The value of the secret represented by the root module's ca_certificate_secret_id is present at the path:
I don't think these certificate secret variables are consistent across the modules yet, so you may want to make a note of that.

2022-04-26 17:00 UTC, anniehedgpeth commented on templates/template.README.md
> +   ```
I would explain this in bullet points as opposed to putting it in a code block, since it's not code.

2022-04-26 19:15 UTC, anniehedgpeth commented on templates/template.README.md
> +        Ubuntu - /usr/local/share/ca-certificates/extra/tfe-ca-certificate.crt
missing bullets

2022-04-26 19:17 UTC, anniehedgpeth commented on templates/template.README.md
> +    - Key Vault secret which contains the Base64 encoded version of a PEM encoded private key for the Virtual Machine Scale Set.
```suggestion
- Valid managed SSL certificate to use with load balancer:
  - <GCP> Create/Import a managed SSL Certificate in Network Services -> Load Balancing to serve as the certificate for the DNS A Record.
  - <AWS> Create/Import a managed SSL Certificate using AWS ACM to serve as the certificate for the DNS A Record.
  - <Azure> An Azure Key Vault in which the following are stored:
    - TFE CA certificate (certificate)
    - Key Vault secret which contains the Base64 encoded version of a PEM encoded public certificate for the Virtual Machine Scale Set
    - Key Vault secret which contains the Base64 encoded version of a PEM encoded private key for the Virtual Machine Scale Set.
```

2022-04-26 19:19 UTC, anniehedgpeth commented on templates/template.README.md
> +    - For GCP  : <https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication>
```suggestion
 7. Authenticate against <provider>. See [instructions](replace with appropriate URL below).
    - <https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli>
    - <https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration>
    - <https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication>
```

2022-04-26 19:21 UTC, anniehedgpeth commented on templates/template.README.md
> +The build should take approximately 10-15 to deploy. Once Terraform completes, give the platform another 10 minutes or so prior to attempting to interact with it in order for all containers to start
```suggestion
The build should take approximately 10-15 minutes to deploy. Once the module has completed, give the platform another 10 minutes or so prior to attempting to interact with it in order for all containers to start up.
```

2022-04-26 20:01 UTC, sandrampeter commented on templates/template.README.md
> +      - The value of the secret represented by the root module's ca_certificate_secret_id is present at the path:
I changed the variable names to those used by this module

2022-04-26 20:02 UTC, sandrampeter commented on templates/template.README.md
> +   ```
I added separate instructions for windows and mac

2022-04-26 20:37 UTC, sandrampeter commented on templates/template.README.md
> +    - Key Vault secret which contains the Base64 encoded version of a PEM encoded private key for the Virtual Machine Scale Set.
slightly changed format as <hidden content> is used to hide data

2022-04-26 20:53 UTC, sandrampeter commented on templates/template.README.md
> +    - For GCP  : <https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#authentication>
<> seems to be hiding content, Hence updated without them

2022-04-27 18:40 UTC, jkerry requested changes

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> +  - Azure - An Azure Key Vault secret which contains the Base64 encoded version of a PEM encoded certificate and private key for mitm proxy server
The order of the clouds in this sub-list should be the same as the order of the clouds in the previous sub-list

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 1. Read the entire README.md for the main module.
Common terminology is root module instead of main module right?

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 1. Read the entire README.md for the main module.
legit question, feel free to shoot it down.

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 3. Clone repository to local machine.
Might want to drop the local machine language here, as it's possible that a consumer is executing these from a CI/CD system or actions operation.

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 6. Modify var.license_file with appropriate local path to the Terraform Enterprise license.
Setting this value is a part of writing the values in step 5. IMO 6 isn't necessary, or if you want to mention this specifically you could say "instantiate required inputs...    ... including the path to the license under the license_file variable value"

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 7. Authenticate against [cloud (aws/azurerm/goggle)] provider. See [instructions](replace with appropriate URL below).
no need for the `( replace with... )` anymore

2022-04-27 18:40 UTC, jkerry commented on templates/template.README.md
> + 9. `terraform plan`
might be worth noting to carefully inspect the plan to ensure that all changes are intended.  it's not exactly liability protection but it's worth noting.

2022-04-27 18:41 UTC, jkerry commented
The more complicated sections like proxy config might be worth publishing a small example video and linking it in the README

2022-04-27 18:59 UTC, anniehedgpeth commented on templates/template.README.md
> + 1. Read the entire README.md for the main module.
Correct, "root module" is what we'd use.

2022-04-27 19:02 UTC, anniehedgpeth commented on templates/template.README.md
> + 7. Authenticate against [cloud (aws/azurerm/goggle)] provider. See [instructions](replace with appropriate URL below).
The `(replace with...)` was my idea because we obviously don't want to include all three clouds' instructions for each example when they'll be in the cloud specific repo. Just wasn't sure how to indicate that it was variable being in a README template. New territory for me.

2022-04-27 19:35 UTC, sandrampeter commented on templates/template.README.md
> + 9. `terraform plan`
Good point! will add

2022-04-27 19:37 UTC, sandrampeter commented on templates/template.README.md
> + 6. Modify var.license_file with appropriate local path to the Terraform Enterprise license.
Added

2022-04-27 19:38 UTC, sandrampeter commented on templates/template.README.md
> + 3. Clone repository to local machine.
updated

2022-04-27 19:39 UTC, sandrampeter commented on templates/template.README.md
> +  - Azure - An Azure Key Vault secret which contains the Base64 encoded version of a PEM encoded certificate and private key for mitm proxy server
updated

2022-04-27 19:39 UTC, sandrampeter commented on templates/template.README.md
> + 1. Read the entire README.md for the main module.
updated

2022-04-27 20:23 UTC, sandrampeter commented on templates/template.README.md
> + 7. Authenticate against [cloud (aws/azurerm/goggle)] provider. See [instructions](replace with appropriate URL below).
i dropped the word "cloud" and updated :  [(aws/azurerm/google)]

2022-04-27 21:25 UTC, jkerry approved these changes

2022-04-27 21:38 UTC, anniehedgpeth approved these changes

2022-04-28 00:05 UTC, merged