change
hashicorp/terraform-random-tfe-utility pull request #20
Opened 2022-05-02 22:14 UTC by sandrampeter

## Background

Adding more prerequisites-> [ASANA](https://app.asana.com/0/1200681690870921/1202158324609536/f)

2022-05-03 14:47 UTC, anniehedgpeth approved these changes
LGTM! Thanks for iterating on this!

2022-05-03 14:48 UTC, jkerry requested changes

2022-05-03 14:48 UTC, jkerry commented on templates/template.README.md
> +-  [(Standalone / Active/Active)] architecture defined by `var.node_count`
This deserves a sub-bullet and more detail I think.  on a first read it sounds like the architecture is defined by node_count, like "1 gets you standalone, 2 gets you active / passive, 3 gets you active active, 4 gets you ... etc"

without being deeply steeped in the form and function of TFE and these repos I wouldn't know what that means

2022-05-03 14:57 UTC, anniehedgpeth commented on templates/template.README.md
> +-  [(Standalone / Active/Active)] architecture defined by `var.node_count`
Good point. What if we simply put links to the docs? 

```suggestion
-  [(Standalone / [Active/Active](https://www.terraform.io/enterprise/install/automated/active-active))] architecture defined by `var.node_count` 
```

2022-05-03 14:58 UTC, sandrampeter commented on templates/template.README.md
> +-  [(Standalone / Active/Active)] architecture defined by `var.node_count`
"defined by `var.node_count`" can be fully dropped if its active-active or standalone. I added this to cover examples that have customisable var.node_count

2022-05-03 18:12 UTC, sandrampeter commented on templates/template.README.md
> +-  [(Standalone / Active/Active)] architecture defined by `var.node_count`
> Good point. What if we simply put a link to the docs?

That's much better, will add it

2022-05-03 21:32 UTC, anniehedgpeth commented on templates/template.README.md
> +- Existing Virtual Machine Image.
These don't need periods at the end of the line if they're not complete sentences. Also, isn't the GCP network called something different? You will want to add that, too.

2022-05-03 21:33 UTC, anniehedgpeth commented on templates/template.README.md
> +- Existing Virtual Machine Image.
RE: periods - That goes for the rest of the bullets which aren't complete sentences, too.

2022-05-03 21:40 UTC, sandrampeter commented on templates/template.README.md
> +- Existing Virtual Machine Image.
Both AWS and GCP has virtual network as VPC. I removed periods.

2022-05-03 21:46 UTC, anniehedgpeth commented on templates/template.README.md
> +1. Navigate to the URL supplied via the `login_url` Terraform output. (It may take several minutes for this to be available after initial deployment. You may monitor the progress of cloud init if des
```suggestion
1. Navigate to the URL supplied via the `login_url` Terraform output. (It may take several minutes for this to be available after initial deployment. You may monitor the progress of cloud init if desired on one of the instances.)
```

2022-05-03 23:17 UTC, anniehedgpeth approved these changes

2022-05-03 23:32 UTC, anniehedgpeth requested changes
As I was reading this in the existing image PR, I realized the wording doesn't make sense as it stands. I can't comment on line 48 because it wasn't changed, but it should say this:

```hcl
- A valid CA certificate and private key for the MITM proxy that are both stored in the [Azure Key Vault / Secrets Manager] as secrets. These should be Base64 encoded versions of a PEM encoded certificate and private key. *(applicable only if MITM proxy is used)*
```
And then the following three lines (49-51) can be omitted.

2022-05-04 13:10 UTC, sandrampeter commented
> ```terraform
> - A valid CA certificate and private key for the MITM proxy that are both stored in the [Azure Key Vault / Secrets Manager] as secrets. These should be Base64 encoded versions of a PEM encoded certificate and private key. *(applicable only if MITM proxy is used)*
> ```

updated!

2022-05-04 16:05 UTC, anniehedgpeth approved these changes

2022-05-04 16:11 UTC, anniehedgpeth requested changes
Tiny change I just saw

2022-05-04 16:11 UTC, anniehedgpeth commented on templates/template.README.md
>      NOTE: `terraform plan` will print out the execution plan which describes the actions Terraform will take in order to build your infrastructure to match the module configuration. If anything in th
```suggestion
    NOTE: `terraform plan` will print out the execution plan which describes the actions Terraform will take in order to build your infrastructure to match the module configuration. If anything in the plan seems incorrect or dangerous, it is safe to abort here and not proceed to `terraform apply`.
```

2022-05-04 16:15 UTC, anniehedgpeth requested changes
One more thing! Just noticed that the Proxy instructions have white space between the numbered items of the list. That should be single spaced. Like this:

```
1. To create a tunnel for Chrome:
   By default, Chrome uses your macOS or Windows proxy. To change your proxy settings from within Chrome, take the following steps: 
   - Open the Chrome toolbar and select "Settings".
   - Scroll down to the bottom of the display. Click on "Show advanced settings".
   - Scroll down to “System” and choose "Open your computer’s proxy settings".
   - Set Chrome proxy server settings.
2. Next, follow the instructions for your operating system to set up your proxy server settings:
   - [macOS](https://support.apple.com/en-ca/guide/mac-help/mchlp2591/mac)
   - [Windows](https://www.dummies.com/article/technology/computers/operating-systems/windows/windows-10/how-to-set-up-a-proxy-in-windows-10-140262/#tab2)
3. SSH to proxy via: `$ ssh -N -p 22 -D localhost:5000 <proxyuser>@<proxyserver> -i ../path/to/id_rsa`
4. The TFE URL is now aacessible via proxy.
```

2022-05-04 16:18 UTC, sandrampeter commented
> One more thing! Just noticed that the Proxy instructions have white space between the numbered items of the list. That should be single spaced. Like this:
> 
> ```
> 1. To create a tunnel for Chrome:
>    By default, Chrome uses your macOS or Windows proxy. To change your proxy settings from within Chrome, take the following steps: 
>    - Open the Chrome toolbar and select "Settings".
>    - Scroll down to the bottom of the display. Click on "Show advanced settings".
>    - Scroll down to “System” and choose "Open your computer’s proxy settings".
>    - Set Chrome proxy server settings.
> 2. Next, follow the instructions for your operating system to set up your proxy server settings:
>    - [macOS](https://support.apple.com/en-ca/guide/mac-help/mchlp2591/mac)
>    - [Windows](https://www.dummies.com/article/technology/computers/operating-systems/windows/windows-10/how-to-set-up-a-proxy-in-windows-10-140262/#tab2)
> 3. SSH to proxy via: `$ ssh -N -p 22 -D localhost:5000 <proxyuser>@<proxyserver> -i ../path/to/id_rsa`
> 4. The TFE URL is now aacessible via proxy.
> ```

np, fixing it here and other repos

2022-05-04 16:37 UTC, anniehedgpeth approved these changes

2022-05-04 16:47 UTC, merged