poc
hashicorp/terraform-random-tfe-utility pull request #3
Opened 2022-01-20 00:35 UTC by anniehedgpeth

## Background

[Asana task](https://app.asana.com/0/0/1201522651525682/f)

This is the repository that houses the proof of concept discussed in detail [here](https://docs.google.com/document/d/1mqlE35M8zXIasGLnxeKGb9ozt0UnOoYVRr2Z7zhh1tM/edit#heading=h.gb4gcg7zw6kf).

This first iteration of the modules in this repo are only functional for the [Azure](https://www.github.com/hashicorp/terraform-azurerm-terraform-enterprise) TFE module. As we iterate, we will add functionality for the [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise) and [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise) TFE modules.

## How was this tested?

The associated passing tests are in this [pull request](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/142) and documented in [here](https://docs.google.com/document/d/1mqlE35M8zXIasGLnxeKGb9ozt0UnOoYVRr2Z7zhh1tM/edit#heading=h.gb4gcg7zw6kf).

Future iterations of this repo will include automated testing.

## TFE Modules

Did you add a new setting?

- [ ] Yes
- [x] No 

If yes, please check each box after you have have added an issue in the TFE modules to add this setting:

- [ ] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [ ] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [ ] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

## This PR makes me feel

![ready for this](https://media.giphy.com/media/YSYkSmLfV74dGCQRz4/giphy.gif)

2022-01-20 16:16 UTC, aaron-lane requested changes
Awesome work! A smattering of comments follow, but nothing too significant (I think).

2022-01-20 16:16 UTC, aaron-lane commented on modules/settings/variables.tf
>  variable "active_active" {
This should be named to match the `enable_active_active` setting (which I think may be currently missing).

2022-01-20 16:16 UTC, aaron-lane commented on modules/settings/variables.tf
> +  default     = []
I think for `var.trusted_proxies` and `var.iact_subnet_list`, we should employ the same `null` default logic to ensure that any potential defaults in Replicated are maintained.

2022-01-20 16:16 UTC, aaron-lane commented on modules/settings/variables.tf
> +  default     = false
Is `BypassPreflightChecks` required or can this also have a default of `null`?

2022-01-20 16:16 UTC, aaron-lane commented on modules/tfe_init/README.md
> +* `active_active` - boolean for whether or not it is an active-active installation
Both of these values can be read from `tfe_configuration`: `hostname` and `enable_active_active`, respectively.

2022-01-20 16:16 UTC, aaron-lane commented on modules/tfe_init/main.tf
> +      no_proxy   = join(",", var.no_proxy)
We may want to defer to `tfe_configuration.extra_no_proxy` for this value 🤔

2022-01-20 16:41 UTC, anniehedgpeth commented on modules/tfe_init/versions.tf
> +  required_version = ">= 0.13"
But the `tfe_init` module doesn't actually create any random resources. Is it still needed?

2022-01-20 16:42 UTC, anniehedgpeth commented on modules/settings/README.md
> +This module does not create any Terraform resources but rather uses `local` variables to form objects that
Oh true. I'll add.

2022-01-20 16:44 UTC, aaron-lane commented on modules/tfe_init/versions.tf
> +  required_version = ">= 0.13"
Oh, sorry! I was thinking this was in `tfe_settings`.

2022-01-20 16:52 UTC, anniehedgpeth commented on modules/settings/main.tf
> +  tfe_configuration             = { for k, v in local.tfe_configuration_remove_null : k => v if v.value != "" }
I did try that, and maybe someone smarter than me can figure out a better way, but when it tries to evaluate if `v.value` is an empty string, it can't seem to evaluate the null values. It errs with:

```
Invalid value for "value" parameter: argument must not be null.
```

So that was why I decided to first take out all of the null values, and then take out the empty strings.

2022-01-20 17:05 UTC, aaron-lane commented on modules/settings/main.tf
> +  tfe_configuration             = { for k, v in local.tfe_configuration_remove_null : k => v if v.value != "" }
Okay, no problem!

2022-01-20 20:34 UTC, anniehedgpeth commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
I thought that if you do not provide a certificate, that it would put a self-signed cert at the path given by `tls_bootstrap_cert_pathname`. So the pathname variable would always be used.

2022-01-20 20:42 UTC, aaron-lane commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
Based on my read of the [documentation](https://help.replicated.com/docs/native/customer-installations/automating/), `TlsBootstrapCert` and `TlsBootstrapKey` are only used when `TlsBootstrapType = "server-path" | "key-cert".

2022-01-20 20:44 UTC, aaron-lane commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
Oh, this also reminded me that we should drop the `pathname` from the `var.tls_bootstrap_*` variables for better alignment with the settings.

2022-01-20 21:09 UTC, anniehedgpeth commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
I see what you're saying now. I'm torn, though, because it _is_ a path and not the actual cert/key, so it's confusing.

2022-01-20 21:11 UTC, aaron-lane commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
Yeah, that's fair. They use the same fields for multiple types of values 😢 Let's leave the pathname designator.

2022-01-20 21:12 UTC, anniehedgpeth commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
To me, this makes sense because the certificate has to exist:

```hcl
    TlsBootstrapCert             = var.certificate_secret == null ? null : var.tls_bootstrap_cert_pathname
    TlsBootstrapKey              = var.certificate_secret == null ? null : var.tls_bootstrap_key_pathname
    TlsBootstrapType             = var.certificate_secret == null ? "self-signed" : "server-path"
```
But maybe I'm not thinking of it properly. What do you recommend?

2022-01-20 21:17 UTC, aaron-lane commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
In general, I think we should avoid adding variables like `certificate_secret` which are only used to make decisions. Non-null values of `tls_bootstrap_cert_pathname` and `tls_bootstap_key_pathname` sufficiently indicate that we are using `server-path` rather than `self-signed`.

2022-01-20 21:18 UTC, aaron-lane commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
That is to say, we should try to limit the amount of knowledge about the implementation details of the TFE modules that this module is aware of.

2022-01-20 22:26 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +  default     = false
Yeah, Replicated defaults it to false, apparently.

2022-01-21 00:39 UTC, anniehedgpeth commented on modules/settings/replicated_config.tf
>      ImportSettingsFrom           = "/etc/ptfe-settings.json"
Makes sense. Thanks for the clarification.

2022-01-21 02:42 UTC, sudomateo reviewed
Left a few comments. Nice work!

2022-01-21 02:42 UTC, sudomateo commented on modules/settings/variables.tf
>    type        = string
I believe this should be a number so that the settings file accurately renders this to a JSON number just like [Replicated expects](https://help.replicated.com/docs/native/customer-installations/automating/).

```suggestion
  type        = number
```

2022-01-21 02:42 UTC, sudomateo commented on modules/settings/variables.tf
> +      var.installation_type == "poc" ||
The `poc` installation mode is going away in April. Just a heads up really just in case you want to update this preemptively.

2022-01-21 02:42 UTC, sudomateo commented on modules/tfe_init/templates/tfe.sh.tpl
> +	lvresize -r -L 40G /dev/mapper/rootvg-varlv
This looks familiar haha.

2022-01-21 02:53 UTC, anniehedgpeth commented on modules/settings/variables.tf
> +      var.installation_type == "poc" ||
Yeah, I considered that, but I just figured that we'd take it out when we remove the `standalone_poc` test.

2022-01-21 02:54 UTC, anniehedgpeth commented on modules/tfe_init/templates/tfe.sh.tpl
> +	lvresize -r -L 40G /dev/mapper/rootvg-varlv
Yes! All credit to @sudomateo ! 🎉

2022-01-21 15:34 UTC, aaron-lane commented on modules/settings/tfe_base_config.tf
> +      value = join(",", var.extra_no_proxy)
`extra_no_proxy` and `iact_subnet_list` should have the same `null` default as `trusted_proxies` 👁️‍🗨️

2022-01-21 15:37 UTC, aaron-lane commented on modules/tfe_init/README.md
> +* `enable_active_active` - boolean for whether or not it is an active-active installation
`enable_active_active` can also be read out of the TFE settings so I don't think we need to include it as a separate argument.

2022-01-21 15:38 UTC, aaron-lane commented on modules/tfe_init/README.md
> +* `enable_active_active` - boolean for whether or not it is an active-active installation
Oh, looks like it's just the README that needs to be updated 😸

2022-01-21 15:43 UTC, aaron-lane commented on modules/tfe_init/variables.tf
>  variable "tfe_license_file_location" {
`tfe_license_file_location`, `tls_bootstrap_cert_pathname`, and `tls_bootstrap_key_pathname` can all be replaced with values from `replicated_configuration`.

2022-01-21 15:53 UTC, aaron-lane commented on modules/settings/tfe_base_config.tf
> +      value = join(",", var.extra_no_proxy)
Don't forget that we also have to check for the `null` values before calling `join()` 😅

2022-01-21 16:16 UTC, aaron-lane approved these changes
This is shaping up really nicely! 🎉

2022-01-21 16:23 UTC, sandrampeter approved these changes
Looks Good, much-needed change :)

2022-01-21 16:23 UTC, sandrampeter commented on modules/tfe_init/templates/tfe.sh.tpl
>  resize_lv() {
Just a thought and no change required. Here the OS files and the application files both reside in rootvg which contains one physical disk of default 100 GB. Most sysadmins would want the applications to reside on a different VG other than root. Also a separate appvg can sometimes helps in implementing any enterprise based backup strategy for disks. I followed a similar approach for [vsphere](https://github.com/hashicorp/ptfe-vsphere-virtual-machine/blob/main/files/prepareOS.sh) and mapped /var/lib/docker to /dev/appvg/applv

2022-01-21 19:04 UTC, anniehedgpeth commented on modules/tfe_init/templates/tfe.sh.tpl
>  resize_lv() {
That's a good call-out, @sandrampeter ! I will make a papercut task to explore this later.

2022-01-21 20:41 UTC, merged