enc_password not needed if external vault used
hashicorp/terraform-random-tfe-utility pull request #6
Opened 2022-01-27 00:02 UTC by anniehedgpeth

## Background

Please include a one or two sentence description of what you're changing and why.

Relates OR Closes #0000

## How has this been tested?

## TFE Modules

### Did you add a new setting?

If no, you may delete these tasks.
If yes, please check each box after you have have added an issue in the TFE modules to add this setting:

- [ ] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [ ] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [ ] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

## This PR makes me feel

![optional gif describing your feelings about this pr]()

2022-02-09 23:33 UTC, jkerry commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
if var.hairpin_addressing is a fixed boolean type it's typically better to leave this as 
`var.hairpin_addressing ? "1" ...`
over
`var.hairpin_addressing == true ? "1" ...`

unless we have a convention preferring otherwise?

2022-02-09 23:34 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
Yeah, I had it like that at first, however, if you have the default value as `null` it complains that it's not a boolean.

2022-02-10 15:09 UTC, jkerry approved these changes

2022-02-10 16:14 UTC, sudomateo reviewed
Looks good overall! I'd expect the boolean variables (like `log_forwarding_enabled`) to default to `false`, not `null`. That way your ternary operators become:

```
var.log_forwarding_enabled ? "1" : "0"
```

I saw a resolved discussion about this but it didn't mention why `null` was chosen. Is the `null` default used for a specific reason?

2022-02-10 16:14 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
>      tls_vers = {
There's no space between this setting and the setting above.

2022-02-10 16:14 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +    vault_store_snapshot = {
I don't see this setting in our `blueprint.yaml`. What does it do?

2022-02-10 16:45 UTC, anniehedgpeth commented
> Looks good overall! I'd expect the boolean variables (like `log_forwarding_enabled`) to default to `false`, not `null`. That way your ternary operators become:
> 
> ```
> var.log_forwarding_enabled ? "1" : "0"
> ```
> 
> I saw a resolved discussion about this but it didn't mention why `null` was chosen. Is the `null` default used for a specific reason?

Yeah, I was torn about that because I didn't want the module to create any settings that weren't intentionally set, thereby falling back to the defaults set in the blueprint. But if you assume the absence of a `true` value is a `false` value, then the module assumes an intentional `false` as opposed to the intentional absence of a setting. Idk, I could be wrong. What do you think?

2022-02-10 23:46 UTC, anniehedgpeth commented
> 

I did an Interactive Install, and when looking at the `ptfe-settings.json` after the install, it did not get populated with any other settings that were defaulted in the blueprint.yml. Therefore, I'll keep the same logic of not adding anything unless explicitly defined, however, I'll take @sandrampeter 's advice and use the `tobool(null)` [function](https://www.terraform.io/language/functions/tobool) to fix the type mismatch error.

2022-02-11 00:02 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +    vault_store_snapshot = {
Removed this. Note for posterity - If it's not in the blueprint, it's not gonna be in `replicatedctl app-config export`.

2022-02-11 02:31 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
FYI @sandrampeter @sudomateo @jkerry 

```hcl
variable "foo" {
  type    = bool
  default = null
}

output "conditional" {
  value = var.foo ? "true" : !var.foo ? "false" : "null"
}
```

This results in:
```hcl
-> terraform apply
╷
│ Error: Null condition
│ 
│   on main.tf line 73, in output "conditional":
│   73:   value = var.foo ? "true" : !var.foo ? "false" : "null"
│     ├────────────────
│     │ var.foo is null
│ 
│ The condition value is null. Conditions must either be true or false.

-> terraform console
> type(var.foo)
bool
> 
```

As you can see, the type of the null valued variable did not need to be converted to a boolean; the `type` constraint on the variable already made it a boolean. But the conditional expression still didn't want to evaluate a `null` valued boolean.

I also tried it in the module, just to be sure, like so:

```hcl
    enc_password = {
      value = tobool(var.extern_vault_enable) ? null : random_id.enc_password.hex
    }

    hairpin_addressing = {
      value = tobool(var.hairpin_addressing) ? "1" : !tobool(var.hairpin_addressing) ? "0" : null
    }
```

```hcl
╷
│ Error: Null condition
│ 
│   on .terraform/modules/settings/tfe_base_config.tf line 49, in locals:
│   49:       value = tobool(var.extern_vault_enable) ? null : random_id.enc_password.hex
│     ├────────────────
│     │ var.extern_vault_enable is null
│ 
│ The condition value is null. Conditions must either be true or false.
╵
╷
│ Error: Null condition
│ 
│   on .terraform/modules/settings/tfe_base_config.tf line 57, in locals:
│   57:       value = tobool(var.hairpin_addressing) ? "1" : !tobool(var.hairpin_addressing) ? "0" : null
│     ├────────────────
│     │ var.hairpin_addressing is null
│ 
│ The condition value is null. Conditions must either be true or false.
```
But no dice.

So what do you think? Keep it as is? Other ideas?

2022-02-11 02:45 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
I think you'll want this conditional:

```
var.foo != null ? var.foo : null
```

That way, you can differentiate between `null`, `false`, and `true`.

2022-02-11 02:48 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
Yes, but the value doesn't equal the boolean; it will need to equal `"1"` or `"0"`.

2022-02-11 02:52 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
Another option is just to use `1` and `0` number values instead of booleans. 🤷‍♀️ 🤷‍♀️ 🤷‍♀️

2022-02-11 03:03 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
Sorry! I forgot about the `"0"` and `"1"` requirement. I think this would work then:

```
var.foo != null ? var.foo ? "1" : "0" : null
```

2022-02-11 03:07 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
The `!= null` logic at the front helps this short circuit. That way, when `foo` is `null`, it doesn't even try to evaluate `foo` as a boolean, and just skips to the last false case of using `null`.

2022-02-11 03:07 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
Oh nice, that does work, thanks! Now I just have to figure out:

```hcl
    enc_password = {
      value = var.extern_vault_enable == true ? null : random_id.enc_password.hex
    }
```

2022-02-11 03:15 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
This is where it starts to get ugly.

```
var.external_vault_enable != null ? var.external_vault_enable ? null : random_id.enc_password.hex : null
```

Perhaps it's worth not caring whether or not a boolean is unset and just explicitly write the defaults to the settings file instead.

2022-02-11 03:25 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.hairpin_addressing == true ? "1" : var.hairpin_addressing == false ? "0" : null
I think it's fine, actually. I'd rather have consistency within the variable logic (what's expected from the user).

2022-02-11 15:19 UTC, sudomateo requested changes
Just minor logic flipping to keep things consistent.

2022-02-11 15:19 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.capacity_concurrency == null ? null : tostring(var.capacity_concurrency)
```suggestion
      value = var.capacity_concurrency != null ? tostring(var.capacity_concurrency) : null
```

2022-02-11 15:19 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.capacity_memory == null ? null : tostring(var.capacity_memory)
```suggestion
      value = var.capacity_memory != null ? tostring(var.capacity_memory) : null
```

2022-02-11 15:19 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.capacity_cpus == null ? null : tostring(var.capacity_cpus)
```suggestion
      value = var.capacity_cpus != null ? tostring(var.capacity_cpus) : null
```

2022-02-11 15:19 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.metrics_endpoint_port_http == null ? null : tostring(var.metrics_endpoint_port_http)
```suggestion
      value = var.metrics_endpoint_port_http != null ? tostring(var.metrics_endpoint_port_http) : null
```

2022-02-11 15:19 UTC, sudomateo commented on modules/settings/tfe_base_config.tf
> +      value = var.metrics_endpoint_port_https == null ? null : tostring(var.metrics_endpoint_port_https)
```suggestion
      value = var.metrics_endpoint_port_https != null ? tostring(var.metrics_endpoint_port_https) : null
```

2022-02-11 15:22 UTC, anniehedgpeth commented on modules/settings/tfe_base_config.tf
> +      value = var.capacity_concurrency == null ? null : tostring(var.capacity_concurrency)
Ah nice catch for consistency; thank you for these, @sudomateo !

2022-02-11 15:27 UTC, sudomateo submitted a review, later dismissed

2022-02-11 15:56 UTC, sandrampeter approved these changes

2022-02-11 16:50 UTC, merged