adding airgap functionality
hashicorp/terraform-random-tfe-utility pull request #9
Opened 2022-02-15 22:42 UTC by anniehedgpeth

## Background

Please include a one or two sentence description of what you're changing and why.

Relates OR Closes #0000

## How has this been tested?

## TFE Modules

### Did you add a new setting?

If no, you may delete these tasks.
If yes, please check each box after you have have added an issue in the TFE modules to add this setting:

- [ ] [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise)
- [ ] [Azure](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise)
- [ ] [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise)

## This PR makes me feel

![optional gif describing your feelings about this pr]()

2022-02-17 17:25 UTC, sandrampeter requested changes
Thank you for working on this!

I have few questions on flag variables - "var.is_airgap" and "var.bootstrap_airgap_installation"

I was wondering if we really need another user input flag for airgap installation if it will be/should be true in all cases where var.airgap_url is set. If var.airgap_url is not set - then its is not an airgap install and setting these flags does not make any difference. 

In the current [GCP](https://github.com/hashicorp/terraform-google-terraform-enterprise/blob/main/variables.tf#:~:text=variable%20%22airgap_url%22%20%7B) and [AWS](https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/main/variables.tf#:~:text=variable%20%22airgap_url%22%20%7B) mod we have only used single variable - var.airgap_url and its value is checked in the install script to run airgap specific func and another local var (is_airgap) is used for [replicated setting](https://github.com/hashicorp/terraform-google-terraform-enterprise/blob/main/modules/user_data/locals.tf#:~:text=is_airgap%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%20var.airgap_url%20%3D%3D%20null%20%3F%20%7B%7D%20%3A%20local.airgap_config)

I believe this way lots of condition checks can be avoided in both install script/settings file

2022-02-17 17:37 UTC, anniehedgpeth commented
I'm going to move this back into draft as I need to add an _unbootstrapped_ example to the Azure module.

2022-02-17 18:11 UTC, jkerry commented on modules/tfe_init/variables.tf
> +  description = "The URL of a Replicated airgap package for Terraform Enterprise."
This description should also mention that the presence of any value here indicates that airgapped installation procedures are followed.  ( This is both a string setting for a url and also a feature flag )

2022-02-17 18:17 UTC, jkerry commented on modules/tfe_init/templates/tfe.sh.tpl
> +%{ if bootstrap_airgap_installation || airgap_url == null ~}
```suggestion
%{ if airgap_url == null ~}
```

2022-02-24 03:43 UTC, sandrampeter commented
Is this tested for external mode ?

2022-02-24 15:21 UTC, anniehedgpeth commented
> Is this tested for external mode ?

@sandrampeter , I did standalone_external, however, it currently has a failure on the main branch, too, so that will need to be troubleshooted later.

2022-02-28 15:15 UTC, sandrampeter approved these changes

2022-02-28 15:17 UTC, merged